#!/bin/sh
[ "$ACTION" == "add" ] || exit 0

token=$(uci get tlgbot.api.token)
chat_id=$(uci get tlgbot.api.chat_id)
api=$(uci get tlgbot.api.url)$token

telegram_log_file=/dev/null

msg="Добавлен новый клиент
IP: $IPADDR
HOSTNAME: $HOSTNAME
MAC: $MACADDR
"
curl -k -s -X POST -H "Charset: UTF-8" $api/sendMessage -d chat_id=$chat_id -d parse_mode=Markdown --data-urlencode text="$msg" &> $telegram_log_file

exit 0